### ISSUE TITLE
Roadmap Github

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-teccaf#1]
[Roadmap Github.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-teccaf/files/13220122/Roadmap.Github.pdf)

**Comment by EdwinOrtiz1412** [comment]
30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
